services:
# DEV
  # Configuration de l'API en dev
  api-dev:
    image: node:22.13.1-alpine3.21
    container_name: api-dev
    volumes:
      - ./api:/api
    ports:
      - 3000:3000
    command: npm run start:dev
    working_dir: /api

  # Configuration de NGINX en dev
  nginx-dev:
    image: nginx:latest
    container_name: nginx-dev
    ports:
      - "80:8080" # Expose le port 80 de NGINX sur le port 8080 de l'hôte
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro # Monte la configuration NGINX
    depends_on:
      - api-dev

# PROD
  # Configuration de l'API en prod
  api-prod:
    image: boris161/api:latest
    container_name: api-prod
    ports:
      - 3000:3000
    command: node dist/main