name: Mon Workflow CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout le code du repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build et Push l'image Docker
      - name: Build and push Docker Image
        run: |
          cd api
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/api:latest

      # 4. Copy docker-compose.yml to VPS
      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: ./docker-compose.yml
          target: ~/api

      # 5. Deploy services
      - name: Deploy services
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/api
            docker-compose up -d nginx-prod
          
      